### PR TITLE
Smart Distancing: Implement FastAPI backend and React frontend skelton

### PR DESCRIPTION
**Pull request by mohammad7t**
Dockerfile-x86 contains build script for frontend.

### CODE REVIEW

**Comment by mhejrati** [comment]
@JsonSadler to help review.

**Comment by mohammad7t** [comment]
@mhejrati @JsonSadler I just added the frontend build script to all Dockerfiles. I have only tested the x86 Dockerfile.

**Comment by mhejrati** [comment]
Merging this PR is pending testing on all hosts. Hopefully, it will be done in 1-2 days!

**Comment by mrn-mln** [comment]
@mhejrati Can I help you? I can test it by edgetpu(usbtpu, coral dev board), jetson nano, and gpu devices.

**Comment by mrn-mln** [comment]
> Merging this PR is pending testing on all hosts. Hopefully, it will be done in 1-2 days!

@mhejrati Can I help you? I can test it by edgetpu(usbtpu, coral dev board), jetson nano, and gpu devices.

**Comment by JsonSadler** [comment]
Wow great! I was away for almost a week, I will check this ASAP

**Comment by mohammad7t** [comment]
This pull request has been moved to the new repo: https://github.com/neuralet/smart-social-distancing/pull/3

**Pull request closed without merging**
