### PR TITLE
use cv.CAP_GSTREAMER for video input

### PR DESCRIPTION
**Pull request by mdegans**
Here is an idea of how to do standard input sources with uridecodebin. rtsp sources will work, local sources will work, even YouTube will work with this techinque if you use something like youtube-dl to extract a valid uri.

This needs testing and more work to support camera sources, but it's an idea of how to do it. Edit: you might want to create a feature branch for this so that whoever picks it up can work from that.

### CODE REVIEW

**Review by mhejrati — APPROVED** [review]

**Comment by JsonSadler** [comment]
I think it was better to merge this into deepstream-gstreamer for more testing, not into the master.

**Comment by mdegans** [comment]
Yeah #64 It's just a very rough untested draft. @JsonSadler will have to get it working and tested first on all platforms. Let me know if there's a platform or something that you don't have available. I don't have a Coral dev board, but I have a USB and PCI TPU, a couple Tegra boards, x86 Nvidia, and just regular plain old x86 to test with.

**Comment by mhejrati** [comment]
Oops :) Sorry it was my mistake merging into master. I thought I am merging
into the deepstream-gstreamer branch :|
Reverted the change and asking @JsonSadler for a new PR.

**Comment by JsonSadler** [comment]
@mdegans do you have any idea about runtime dependencies, including which gstreamer plugins to install? I am going to install all the plugins for now, but I am almost sure that it's not necessary.

**Comment by JsonSadler** [comment]
> @mdegans do you have any idea about runtime dependencies, including which gstreamer plugins to install? I am going to install all the plugins for now, but I am almost sure that it's not necessary.

For putting in the docerfiles, of course. It is not working with the current setup, I am working on it.

**Comment by JsonSadler** [comment]
Oh never mind @mdegans , just saw your other comment in issue #67 , will let you know if could get it working the Nvidia's guide for Accelerated GStreamer on jetson you mentioned there.

**Pull request merged**
