### PR TITLE
Gstreamer encoder fixes

### PR DESCRIPTION
**Pull request by mdegans**
* move videoconvert since nvidia has it's own element for that
* modify/add encoder lines as appropriate for platforms

### CODE REVIEW

**Comment by mdegans** [comment]
note: i'm about to update this with some more changes. the x264 encoder and the vaapi are not in teh dockerfile so I added them and am testing now. a pipeline with "appsrc ! fakesink" works. Also moved the end of the pipeline back so the encoder string is just the encoder and coverter. will push soon.

**Comment by mdegans** [comment]
also, for _vaapi_ hardware decode to work in docker a device needs to be passed through, so the readme usage will need to change. notes on that here:
https://jellyfin.org/docs/general/administration/hardware-acceleration.html#acceleration-on-docker

**Comment by mdegans** [comment]
So i got it making videos, but hlssink won't respect the playlist location set to an absolute path. I found a [thread](#  i have to say the documentation for hlssink is exceptionally terrible) with some unhelpful response saying 'read the documentation' but the documentation on this really isn't that great  (what exactly is "location" is it a filename? is it a uri? is it a dir?) I'm going to checkout the source next.

**Comment by mdegans** [comment]
```C
  if (!g_file_set_contents (sink->playlist_location,
          playlist_content, -1, &error)) {
```
It looks fine to me. it should write the m3u8 to that absolute path (but it's not). The property sets sink->playlist_location and that's passed directly to this function.

"location" simply sets "location" on the multifilesink and that part works, so the video goes where you point it. it may be g_file_set_contents doesn't support absolute paths but I'm pretty sure it does and the docs don't say it doesn't. I will investigate more.

**Comment by mdegans** [comment]
So I think i figured it out. outside docker, i tried:
```
gst-launch-1.0 videotestsrc ! videoconvert ! x264enc speed-preset=ultrafast ! hlssink max-files=5 playlist-root=http://127.0.0.1:8080 location=/tmp/video_%05d.ts playlist-location=/tmp/playlist.m3u8
```
And that works. It writes a playlist and the .ts files to /tmp as it should.

@mhsekhavat

I think the issue here is that a playlist can't be generated until there is a complete file, and since the frame rate is low, it has to wait for the default 15 seconds of video before it writes the playlist. Since it's reading the fps from the input video, it's 30fps, so 450 frames.

**Comment by mohammad7t** [comment]
Thank you so much @mdegans . The pull request look great. 
I am facing a problem, though. When I try to run `x86` docker image, I get the following error:

```
output pipeline: appsrc ! videoconvert ! x264enc speed-preset=ultrafast ! hlssink max-files=5 playlist-root=http://localhost/ location=/tmp/video_%05d.ts playlist-location=/tmp/playlist.m3u8
OpenCV: FFMPEG: tag 0x00000000/'????' is not supported with codec id 14 and format 'hls / Apple HTTP Live Streaming'
error: XDG_RUNTIME_DIR not set in the environment.
0:00:00.264865657    26 0x55e95fcd2aa0 ERROR                default gstvaapi.c:254:plugin_init: Cannot create a VA display
```
Do you know what the problem is?

**Comment by mdegans** [comment]
Yes. For vaapi encoders to work some --device flags need to be passed to docker.

https://github.com/neuralet/neuralet/pull/112#issuecomment-631038043

You're seeing that because the x264enc is trying to use vaapi first, failing, and falling back on software. At least for me it's still making .ts files in /tmp (use `docker exec` to enter the running container), but I haven't tested if they were playable. They were outside of the container with a test pipeline.

There are other options like the omx series of encoders / decoders. I was experimenting with them later yesterday to try and avoid the --device flags but they may still be necessary.

If the `docker run` gets too long, it may be preferable to add run scripts, rather than expect somebody copy and paste all that or type it out.

**Comment by mdegans** [comment]
Actually, I had a closer look at that error. "FFMPEG: tag 0x00000000/'????' is not supported", should not be there, iirc. I will double check when I get to my workstations after breakfast and walking my dogs.

**Comment by mohammad7t** [comment]
Awesome. I added `--device /dev/dri/renderD128:/dev/dri/renderD128 --device /dev/dri/renderD129:/dev/dri/renderD129` to my docker run command but still got the same errors. Can you please tell me what flags work for you?

**Comment by mdegans** [comment]
So, I checked and even with the error it's making video as it should at `video_root`

```
root@410dabf2f95f:/tmp# ls
playlist.m3u8  video_00000.ts  video_00001.ts  video_00002.ts  video_000
```

The error is because cv.CAP_GSTREAMER isn't explicitly specified, so it's still trying to encode from the end of the pipeline but it can't because it's a hlssink and not providing any video with a valid fourcc tag. Pushing a fix now.

**Comment by mdegans** [comment]
> Awesome. I added `--device /dev/dri/renderD128:/dev/dri/renderD128 --device /dev/dri/renderD129:/dev/dri/renderD129` to my docker run command but still got the same errors. Can you please tell me what flags work for you?

I haven't tested the hardware encode yet, but it ~appears x264 will try to use vaapi~ (**edit**: it won't. it's just the plugin failing to load since the gstreamer registry checks them all at start.) if it's available (at last with the ultrafast preset), so we may be able to just use that encoder all the time on nearly every platform except Tegra which doesn't support ffmpeg hardware encode currently. I will try to use a vaapi encoder explicitly with the `--device` flags next and let you know what I can get working.

**Comment by mdegans** [comment]
So even with the devices passed in, I get `Cannot create a VA display`, causing the vaapi plugin to fail to load, causing the pipeline to fail. I'm going to see if I can get the omx hardware encoders to work since I'm not sure they rely on vaapi.

Edit: the solution may be here:

https://jellyfin.org/docs/general/administration/hardware-acceleration.html#debian-docker-nvidia

They add the deprecated nvidia runtime into daemon.json manually and set it as the default runtime, but I don't recommend we do this since it might break other containers and lead to undefined behavior. Gonna try omx first for sure.

Edit: it may not require being set as the defualt, but it might require adding nvidia to the list of available runtimes:
```
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
```

If you're like, you can try that while I work on omx. It seems like a lot of setup to get it working with vaapi in docker.

**Comment by mdegans** [comment]
So it looks like omx tries to use vaapi as well. About the only thing that doesn't is deepstream. That one is powered by nvidia proprietary magic. That may be the preferred option for x86/nvidia. I do have x86/AMD to test with, on which vaapi may work with the devices passed through.

Edit: installing docker now on my intel/amd box (Hades Canyon). amdgpu is the driver it's using.

**Comment by mdegans** [comment]
So it appears the instructions on that page don't work. Outside the container I get:
```
 $ vainfo
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Mesa Gallium driver 20.0.4 for AMD VEGAM (DRM 3.35.0, 5.4.0-29-generic, LLVM 9.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
And inside I get:
```
root@skull:/repo/applications/smart-distancing# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
error: failed to initialize display
```
It may be that vaapi requires x11 -- meaning we proably need to use --network host and define $DISPLAY inside the contaner.
lshw sees the cards:
```
root@99eecdcc12a7:/repo/applications/smart-distancing# lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Polaris 22 [Radeon RX Vega M GH]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: c0
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: iomemory:200-1ff iomemory:210-20f irq:169 memory:2000000000-20ffffffff memory:2100000000-21001fffff ioport:e000(size=256) memory:db500000-db53ffff memory:c0000-dffff
  *-display
       description: Display controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list
       configuration: driver=i915 latency=0
       resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:168 memory:2ffe000000-2ffeffffff memory:2fa0
```

**Comment by mdegans** [comment]
So, I found a reddit thread indicating that the `mesa-va-drivers` package might need to be installed, so I'm gonna try that out now. Software encode works fine for now, but it's not ideal.

**Comment by mdegans** [comment]
OMG it works!

There are still warnings because x11 variables expected aren't there, but it's encoding, and it's using vaapi. `mesa-va-drivers` solved it. pushing changes now.

**Comment by rkgits** [comment]
Nice!

**Comment by mdegans** [comment]
> Nice!

Yeah. I gotta find that reddit thread again and upvote that answer. This might even work on x86/nvidia, although deepstream will probably perform better there.

**Comment by mdegans** [comment]
btw, it works in rootless docker if you're in the proper groups to access the devices (video, render).

**Comment by mohammad7t** [comment]
Thank you @mdegans ! I am still getting the following error when I build and run your branch's dockerfile:
```
error: XDG_RUNTIME_DIR not set in the environment.
0:00:00.184482232    26 0x55d7cb387aa0 ERROR                default gstvaapi.c:254:plugin_init: Cannot create a VA display
0:00:00.260776274     1 0x7fdae41e1cf0 ERROR           GST_PIPELINE grammar.y:816:priv_gst_parse_yyparse: no element "vaapih264enc"
0:00:00.260800254     1 0x7fdae41e1cf0 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no sink [source=@0x7fdae42a40d0]
0:00:00.261589706     1 0x7fdae41e1cf0 ERROR           GST_PIPELINE grammar.y:901:priv_gst_parse_yyparse: link has no source [sink=@0x7fdae41141b0]
[ WARN:0] global /tmp/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (1424) open OpenCV | GStreamer warning: error opening writer pipeline: no element "vaapih264enc"
```

**Comment by mohammad7t** [comment]
> btw, it works in rootless docker if you're in the proper groups to access the devices (video, render).

I assume `--privilege` should be enough for having access to the devices. The error above is with `--privilege` flag. Should I do anything else?

**Comment by mdegans** [comment]
> > btw, it works in rootless docker if you're in the proper groups to access the devices (video, render).
> 
> I assume `--privilege` should be enough for having access to the devices. The error above is with `--privilege` flag. Should I do anything else?

You should only need:
```
docker run -it --rm --name sd --device /dev/dri/card1 --device /dev/dri/renderD129 -v $PWD/../..:/repo -p 8080:8080 (image name)
```

but you might need to adjust your device names (eg. card0 and renderD128). No --privileged should be necessary. Docker runs as root by default in any case, and root inside is the same root as outside (except in the case of rootless docker), so if you pass in a `--device` it will have full access to it. What --privileged does is pass through *all* devices on the system, including dangerous thigns like block devices.

At some point we may wish to reconsider how the containers are launched so root isn't used at all. We can either drop to a `USER` inside the dockerfile or add instructiions to use the `--user` flag mapped to a desired uid on the host (as the tensorflow image does). Running as root, espeically if these containers are connected to the web, is risky.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

**Comment by mdegans** [comment]
If you're still having issues with that, @mhsekhavat let me know. I haven't tested it on Nvidia. Only on Intel/AMD

On whatever/Nvidia I recommend we use DeepStream.

**Comment by mohammad7t** [comment]
@mdegans yes I am still having the same issue with *Intel*. I use `--device /dev/dri/card0 --device /dev/dri/card1 --device --device /dev/dri/renderD128 /dev/dri/renderD129` flags. Those are all devices I see in /dev/dri/

**Comment by mdegans** [comment]
```
--device /dev/dri/card0 --device /dev/dri/card1 --device --device /dev/dri/renderD128 /dev/dri/renderD129
```
@mhsekhavat 

Can you clarify, in /dev/dri, you have two cards or one?

Can you try:
```
--device /dev/dri/card0 --device /dev/dri/renderD128
```
If you have only one card that _should_ work. If you have two, it should be card1 and renderD129.

Just to make sure you have kernel support and drivers for all this, can you test this works on the outside:
```
sudo apt install vainfo
vainfo
```
And post what pops out?

I have Intel on my system, and it shows up in /dev, but I'm not sure it's available for use becuase of my unique configuration which has an AMD gpu integrated (Hades Canyon). Intel did _not_ work for me passing through my `card0` and `d128`, but that's common when there are two GPUs. On my system I only passed through the second, AMD GPU and it worked.

**Comment by mohammad7t** [comment]
Please see the result of following commands in on laptop:
```
$ find /dev/dri 
/dev/dri
/dev/dri/card1
/dev/dri/renderD129
/dev/dri/by-path
/dev/dri/by-path/pci-0000:01:00.0-render
/dev/dri/by-path/pci-0000:01:00.0-card
/dev/dri/by-path/pci-0000:00:02.0-card
/dev/dri/by-path/pci-0000:00:02.0-render
/dev/dri/card0
/dev/dri/renderD128
```

```
$ vainfo
vaInitialize failed with error code -1 (unknown libva error),exit
```

All of the following args give me the same error:
* `--device /dev/dri/card0 --device /dev/dri/renderD128`
* `--device /dev/dri/card1 --device /dev/dri/renderD129`
* `--device /dev/dri/card0 --device /dev/dri/renderD128 --device /dev/dri/card1 --device /dev/dri/renderD129`

**Comment by mdegans** [comment]
If you ran vainfo outside of docker and it gave that info it means vaapi may have a problem on your system.

Can you run `sudo lshw -C video`:
```
 $ sudo lshw -C video
[sudo] password for mdegans: 
  *-display                 
       description: VGA compatible controller
       product: Polaris 22 XT [Radeon RX Vega M GH]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: c0
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=amdgpu latency=0 mode=3840x2160 visual=truecolor xres=3840 yres=2160
       resources: iomemory:200-1ff iomemory:210-20f irq:169 memory:2000000000-20ffffffff memory:2100000000-21001fffff ioport:e000(size=256) memory:db500000-db53ffff memory:c0000-dffff
  *-display
       description: Display controller
       product: HD Graphics 630
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list
       configuration: driver=i915 latency=0
       resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:168 memory:2ffe000000-2ffeffffff memory:2fa0000000-2fafffffff ioport:f000(size=64)
```

**Comment by mohammad7t** [comment]
here is the output:
```
$ sudo lshw -C video
  *-display                 
       description: 3D controller
       product: GM107M [GeForce GTX 960M]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list
       configuration: driver=nvidia latency=0
       resources: irq:16 memory:93000000-93ffffff memory:80000000-8fffffff memory:90000000-91ffffff ioport:4000(size=128)
  *-display
       description: VGA compatible controller
       product: HD Graphics 530
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:142 memory:92000000-92ffffff memory:a0000000-afffffff ioport:5000(size=64) memory:c0000-dffff
```

Maybe I should configure something. I tried vainfo on another workstation and got this error:
```
$ vainfo
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
vaInitialize failed with error code -1 (unknown libva error),exit
```
I get a similar error with `sudo vainfo` too.

**Comment by mdegans** [comment]
I get the same error on my Nvidia 18.04 box:
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
vaInitialize failed with error code -1 (unknown libva error),exit
```
18.04 box with old amd card (Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]):
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
error: failed to initialize display
```
The box that works is 20.04 with amd and intel. What Ubuntu version are you running? [I've heard](https://bbs.archlinux.org/viewtopic.php?id=238517) that mixed Nvidia+Intel on a laptop with Optimus has issues. In general, i've found HW accel on linux is hit or miss, but it's better recently.

I think it's best we test other options than vaapi since it only seems to work on 20.04 with AMD. Very strangely, when I ssh into my box I can see the Intel card but not the AMD:
```
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
So yeah. It's probably still worth supporting but maybe we should make `x264` the default on x86 with notes on how to enable hw accel for platforms that (might) support it. With Linux there is almost always a way, it's just a question of (a lot of) trial and error and Googling. You've provided a way to swap out encoders with literally any element gstreamer suppports, so that's a big win in my book. Wdyt @mhsekhavat ?

**Comment by mohammad7t** [comment]
@mdegans My laptop has Archlinux and the other workstation is using Ubuntu 18.04.
I agree we can document how to support vaapi but switch to a more available encoder as the default encoder. Do you suggest any other encoders to use?
Another option is to keep using motion-JPEG (instread of gstreamer) *for server-to-client streaming* with a more efficient streaming mechanism. I am working on it.

**Comment by mdegans** [comment]
I suggest x264enc as the default with the ultrafast preset. It's what Google uses with edgetpuvision on the Coral dev board so we know it's effecient to work on embedded architectures -- certainly on x86.

Having a fallback is good, but there are disadvantages to mjpeg over h264 (eg. mjpeg is a very old spatial only codec, while h264 is a recent spatio-temporal codec). Also, jpeg hardware encode/decode is even less widely available. Anyway, we'll discuss it at 12.

**Comment by mohammad7t** [comment]
I moved the gstreamer barnch to the new repository: https://github.com/neuralet/smart-social-distancing/tree/gstreamer

**Pull request merged**
